version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      # Manter segurança habilitada (padrão) - usar admin:admin
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks: [observability]
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=false
      - "OPENSEARCH_USERNAME=admin"
      - "OPENSEARCH_PASSWORD=admin"
    ports:
      - "5601:5601"
    depends_on: [opensearch]
    networks: [observability]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otelcol/config.yml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on: [opensearch]
    networks: [observability]

networks:
  observability:
    driver: bridge

volumes:
  opensearch-data:

